[package]
name = "Rustris"
description = "Rust tetris clone"
version = "0.1.0"
authors = ["realjasomo <jason.cramer6@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
